on: push

jobs: 
    build: 
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Build index.html file
              run: python build.py

            - name: Upload built files
              uses: actions/upload-pages-artifact@v3
              with:
                path: out/
    deploy:
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        needs: build
        permissions: 
            pages: write
            id-token: write
        steps:
            - name: Deploy to GitHub pages
              uses: actions/deploy-pages@v4
    opencommit:
        timeout-minutes: 10
        name: OpenCommit
        runs-on: ubuntu-latest
        permissions: write-all
        steps:
          - name: Setup Node.js Environment
            uses: actions/setup-node@v2
            with:
              node-version: '16'
          - uses: actions/checkout@v3
            with:
              fetch-depth: 0
          - uses: di-sukharev/opencommit@github-action-v1.0.4
            with:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
            env:
              # set openAI api key in repo actions secrets,
              # for openAI keys go to: https://platform.openai.com/account/api-keys
              # for repo secret go to: <your_repo_url>/settings/secrets/actions
              OCO_API_KEY: ${{ secrets.OCO_API_KEY }}
    
              # customization
              OCO_TOKENS_MAX_INPUT: 4096
              OCO_TOKENS_MAX_OUTPUT: 500
              OCO_OPENAI_BASE_PATH: ''
              OCO_DESCRIPTION: false
              OCO_EMOJI: false
              OCO_MODEL: gpt-4o
              OCO_LANGUAGE: en
              OCO_PROMPT_MODULE: conventional-commit
